config/routes.rb
Rails.application.routes.draw do
  resources :gardens do
    resources :plants, only: [:new, :create]
  end
  resources :plants, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants, dependent: :destroy # @garden.plants
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden # @plant.garden
  validates :name, presence: true
  validates :banner_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: [:show, :edit, :update, :destroy]

  # GET /gardens
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1
  def show
  end

  # GET /gardens/new
  def new
    @garden = Garden.new
  end

  # GET /gardens/1/edit
  def edit
  end

  # POST /gardens
  def create
    @garden = Garden.new(garden_params)

    if @garden.save
      redirect_to @garden, notice: 'Garden was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /gardens/1
  def update
    if @garden.update(garden_params)
      redirect_to @garden, notice: 'Garden was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /gardens/1
  def destroy
    @garden.destroy
    redirect_to gardens_url, notice: 'Garden was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garden
      @garden = Garden.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def garden_params
      params.require(:garden).permit(:name, :banner_url)
    end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

  def new
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new
  end

  def create
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new(plant_params)
    @plant.garden = @garden
    if @plant.save
      redirect_to garden_path(@garden)
    else
      render :new
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @garden = @plant.garden
    @plant.destroy
    redirect_to garden_path(@garden)
  end

  private


  def plant_params
    params.require(:plant).permit(:name, :banner_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/_form.html.erb
<%= simple_form_for(@garden) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :banner_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/gardens/edit.html.erb
<h1>Editing Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Show', @garden %> |
<%= link_to 'Back', gardens_path %>

app/views/gardens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gardens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Banner url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gardens.each do |garden| %>
      <tr>
        <td><%= garden.name %></td>
        <td><%= garden.banner_url %></td>
        <td><%= link_to 'Show', garden %></td>
        <td><%= link_to 'Edit', edit_garden_path(garden) %></td>
        <td><%= link_to 'Destroy', garden, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Garden', new_garden_path %>

app/views/gardens/new.html.erb
<h1>New Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Back', gardens_path %>

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @garden.banner_url %>);">
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>
</div>

<div class='mt-3'>
  <% @garden.plants.each do |plant| %>
    <div class="card-category my-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= plant.banner_url %>)">
      <%= plant.name %>
      <%= link_to "Delete this plant", plant_path(plant), method: :delete, data: {confirm: "Are you sure?"}%>
    </div>
  <% end %>
</div>

<%= link_to 'Edit', edit_garden_path(@garden) %> |
<%= link_to 'Back', gardens_path %>
<%= link_to "Add a plant", new_garden_plant_path(@garden)  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParksAndPlants549</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plants/new.html.erb
<div class="container">
  <%= simple_form_for [@garden, @plant] do |f|  %>
  <%= f.input :name %>
  <%= f.input :banner_url %>
  <%= f.submit %>
  <% end %>
</div>